### ISSUE TITLE
With multiple slots, map availability is not calculated correctly

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commons-booking-2#597]
<img width="1151" alt="Bildschirmfoto 2020-03-06 um 14 24 02" src="https://user-images.githubusercontent.com/4009931/76087297-281e9180-5fb6-11ea-9c2c-28f6ee51d105.png">

* **expected:** calendar should show availability (indicator dot) for each day (2.,3.,4.,), since there is a slot not covered by a booking. 
* **behaviour:** does only show availability for 3rd only

**Comment by anewholm** [comment]
The situation is more severe than that actually. The Strategy is pulling all data for all days and plotting them in the calendar. So, if there are 2 slots per day, it shows 2 indicators in the day for the item. I am assuming we want 1. 

Also, as spotted, the Map is using CB2_ItemsFirstAvailability which appears to be pulling out the first slot only and then removing it because it is booked. That is a bug. It should find the first _available_ slot.

![image](https://user-images.githubusercontent.com/708045/76980968-94987980-6942-11ea-8364-ea28cc172a0f.png)

**Comment by anewholm** [comment]
![image](https://user-images.githubusercontent.com/708045/76981251-0244a580-6943-11ea-8034-38d16f4ab160.png)

**Comment by anewholm** [comment]
So, yes, problems confirmed!
